/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Model.Ferramentas;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author li058737
 */
public class CadastroFerramentas extends javax.swing.JFrame {

    /**
     * Creates new form cadastroferramentas
     */
    private Ferramentas objetoFerramenta;

    public CadastroFerramentas() {
        initComponents();
        this.objetoFerramenta = new Ferramentas();
        carregaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cadastros = new javax.swing.JButton();
        ferramentas = new javax.swing.JButton();
        eventos = new javax.swing.JButton();
        emprestimos = new javax.swing.JButton();
        amigos = new javax.swing.JButton();
        adicionarFerramenta = new javax.swing.JButton();
        editarFerramenta = new javax.swing.JButton();
        excluirFerramenta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFerramenta = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Ferramentas");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro Ferramentas");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cadastros.setBackground(new java.awt.Color(102, 153, 255));
        cadastros.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        cadastros.setForeground(new java.awt.Color(51, 51, 51));
        cadastros.setText("Cadastros");
        cadastros.setBorderPainted(false);
        cadastros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrosActionPerformed(evt);
            }
        });

        ferramentas.setBackground(new java.awt.Color(102, 153, 255));
        ferramentas.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        ferramentas.setForeground(new java.awt.Color(51, 51, 51));
        ferramentas.setText("Ferramentas");
        ferramentas.setBorderPainted(false);
        ferramentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ferramentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ferramentasActionPerformed(evt);
            }
        });

        eventos.setBackground(new java.awt.Color(255, 255, 255));
        eventos.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        eventos.setForeground(new java.awt.Color(51, 51, 51));
        eventos.setText("Eventos");
        eventos.setBorderPainted(false);
        eventos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventosActionPerformed(evt);
            }
        });

        emprestimos.setBackground(new java.awt.Color(255, 255, 255));
        emprestimos.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        emprestimos.setForeground(new java.awt.Color(51, 51, 51));
        emprestimos.setText("Empréstimos");
        emprestimos.setBorderPainted(false);
        emprestimos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        emprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emprestimosActionPerformed(evt);
            }
        });

        amigos.setBackground(new java.awt.Color(255, 255, 255));
        amigos.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        amigos.setForeground(new java.awt.Color(51, 51, 51));
        amigos.setText("Amigos");
        amigos.setBorderPainted(false);
        amigos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        amigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amigosActionPerformed(evt);
            }
        });

        adicionarFerramenta.setBackground(new java.awt.Color(255, 255, 255));
        adicionarFerramenta.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        adicionarFerramenta.setForeground(new java.awt.Color(51, 51, 51));
        adicionarFerramenta.setText("Adicionar Ferramenta");
        adicionarFerramenta.setBorderPainted(false);
        adicionarFerramenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        adicionarFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarFerramentaActionPerformed(evt);
            }
        });

        editarFerramenta.setBackground(new java.awt.Color(255, 255, 255));
        editarFerramenta.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        editarFerramenta.setForeground(new java.awt.Color(51, 51, 51));
        editarFerramenta.setText("Editar Ferramenta");
        editarFerramenta.setBorderPainted(false);
        editarFerramenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editarFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarFerramentaActionPerformed(evt);
            }
        });

        excluirFerramenta.setBackground(new java.awt.Color(255, 255, 255));
        excluirFerramenta.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        excluirFerramenta.setForeground(new java.awt.Color(51, 51, 51));
        excluirFerramenta.setText("Excluir Ferramenta");
        excluirFerramenta.setBorderPainted(false);
        excluirFerramenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        excluirFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirFerramentaActionPerformed(evt);
            }
        });

        jTableFerramenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Marca", "Custo (R$)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableFerramenta);
        if (jTableFerramenta.getColumnModel().getColumnCount() > 0) {
            jTableFerramenta.getColumnModel().getColumn(0).setResizable(false);
            jTableFerramenta.getColumnModel().getColumn(1).setResizable(false);
            jTableFerramenta.getColumnModel().getColumn(2).setResizable(false);
            jTableFerramenta.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("->");

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("->");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(amigos, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ferramentas, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cadastros, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(emprestimos, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(eventos, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(adicionarFerramenta)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(editarFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(excluirFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 35, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastros, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emprestimos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eventos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ferramentas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amigos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionarFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(excluirFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ferramentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ferramentasActionPerformed

    }//GEN-LAST:event_ferramentasActionPerformed

    private void eventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventosActionPerformed
        new View.EventosCalendario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_eventosActionPerformed

    private void emprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprestimosActionPerformed
        new View.EmprestimosTela().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_emprestimosActionPerformed

    private void amigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amigosActionPerformed
        CadastrosAmigos cadami = new CadastrosAmigos();
        cadami.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_amigosActionPerformed

    private void adicionarFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarFerramentaActionPerformed

        AdicionarFerramenta addfer = new AdicionarFerramenta();
        addfer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adicionarFerramentaActionPerformed

    private void editarFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarFerramentaActionPerformed
        EditarFerramenta editferramenta = new EditarFerramenta();
        editferramenta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editarFerramentaActionPerformed

    private void excluirFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirFerramentaActionPerformed
        ExcluirFerramenta excluirfer = new ExcluirFerramenta();
        excluirfer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_excluirFerramentaActionPerformed

    private void cadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrosActionPerformed
        new Cadastros().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cadastrosActionPerformed

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("unchecked")
    public void carregaTabela() {
        DefaultTableModel modelo = (DefaultTableModel) this.jTableFerramenta.getModel();
        modelo.setNumRows(0);

        ArrayList<Ferramentas> listaFerramentas = new ArrayList<>();
        listaFerramentas = objetoFerramenta.getListaFerramentas();

        for (Ferramentas f : listaFerramentas) {
            modelo.addRow(new Object[]{
                f.getId(),
                f.getNome(),
                f.getMarca(),
                f.getCustoAquisicao()
            });
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFerramentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarFerramenta;
    private javax.swing.JButton amigos;
    private javax.swing.JButton cadastros;
    private javax.swing.JButton editarFerramenta;
    private javax.swing.JButton emprestimos;
    private javax.swing.JButton eventos;
    private javax.swing.JButton excluirFerramenta;
    private javax.swing.JButton ferramentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableFerramenta;
    // End of variables declaration//GEN-END:variables
}
